### ISSUE TITLE
Zoom issues

### ISSUE THREAD

**Issue by sekwah41** [DeflatedPickle/Rawky#21]
When you are zoomed the pen doesn't draw where it should

**Comment by DeflatedPickle** [comment]
I am aware of this, and it's due to scaling the grid like [this](https://github.com/DeflatedPickle/Rawky/blob/master/src/main/kotlin/com/deflatedpickle/rawky/component/PixelGrid.kt#L173) then translating the current mouse point to the top-left like [this](https://github.com/DeflatedPickle/Rawky/blob/master/src/main/kotlin/com/deflatedpickle/rawky/component/PixelGrid.kt#L116-L117), but I never scale it, since you can't scale a single point.

There is a FIXME for it, [here](https://github.com/DeflatedPickle/Rawky/blob/master/src/main/kotlin/com/deflatedpickle/rawky/component/PixelGrid.kt#L115), but I genuinely don't know how to fix it. It's one of those things that when I think about it, my mind goes blank. Unless I can just translate by the `pixelSize` multiplied by the `scale`... huh, that might be crazy enough to work.
